services:
  db:
    image: mariadb:10.11
    container_name: fox_shelter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword123!
      MYSQL_DATABASE: FoxShelterDB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pRootPassword123!"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: fox_shelter_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=FoxShelterDB;Uid=root;Pwd=RootPassword123!;
      - Jwt__Secret=Cheie_Ultra_Secreta_Si_Foarte_Lunga_De_Minim_64_Caractere_Asigura_Te_Ca_E_Lunga!!!
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./wwwroot:/app/wwwroot

  proxy:
    image: nginx:latest
    container_name: fox_proxy
    restart: always
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/localhost.pem:/etc/nginx/certs/localhost.pem:ro
      - ./certs/localhost-key.pem:/etc/nginx/certs/localhost-key.pem:ro
      - ./wwwroot:/app/wwwroot:ro
    depends_on:
      - api

volumes:
  db_data: